version: 0.0
os: linux
files: 
- source: /
  destination: /home/ec20user/express-app
hooks:
  ApplicationStop: 
   - location: scripts/application_stop.sh
   - timeout: 300
   - runas: ec2-user
  beforeinstall:
   - location: scripts/before_install.sh
   timeout: 300
   runas: ec2-user
ApplicationStart:
 - location: scripts/application_start.sh
   timeout: 3000
   runas: ec2-user 